### ISSUE TITLE
create schema for Rooms

### ISSUE THREAD

**Issue by yancey1204** [JavaScriptAcademy/Whisper-Server#6]

**Comment by CyrusCai** [comment]
**Rooms**
        _id
        name
        roomImage
        discription
        topic
        ownerId
        [audios]
            _id 
            createrName : User.nickname
            createdTime: new Date()
            length
            voiceType( Reserve )
        [menbers](Reserved)
            User._id

**Comment by CyrusCai** [comment]
change audios to messages
